# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project04' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'RealmSwift'

  # Pods for project04

end
